name: Build and Push Docker image to GHCR

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: terraspace
  TERRASPACE_VERSION: '2.2.18'
  TERRAFORM_VERSION: '1.13.3'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version variables
        id: vars
        run: |
          # Use workflow_dispatch inputs if present, else fallback to Dockerfile parsing or defaults
          TERRASPACE_VERSION="${{ github.event.inputs.TERRASPACE_VERSION || '2.2.18' }}"
          TERRAFORM_VERSION="${{ github.event.inputs.TERRAFORM_VERSION || '1.13.1' }}"
          echo "TERRASPACE_VERSION=$TERRASPACE_VERSION" >> $GITHUB_ENV
          echo "TERRAFORM_VERSION=$TERRAFORM_VERSION" >> $GITHUB_ENV
          echo "TAG=${TERRASPACE_VERSION}-bookworm-${TERRAFORM_VERSION}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            TERRASPACE_VERSION=${{ env.TERRASPACE_VERSION }}
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
